import type { Metadata } from "next";
import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import Navbar from "@/components/_layout/Navbar/Navbar";
import FAQ from "@/components/_essential/Faq";
import Footer from "@/components/_layout/Footer/Footer";
import Provider from "@/providers/ProgressBarProvider";
import { AbhayaLibre, BebasNeue, NewYork, urbanist } from "./fonts";
import ContextProvider from "@/providers/ContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${NewYork.variable} ${AbhayaLibre.variable} ${BebasNeue.variable}`}
      >
        <ContextProvider>
          <Navbar />
          {children}
          <FAQ />
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
